### ISSUE TITLE
Box missing border radius

### ISSUE THREAD

**Issue by stubbo** [HexaneNetworks/gamepanel-dev#10]
**Describe the bug**
missing a border radius ocd sorry 😭 

**To Reproduce**
Go to [panel](https://gamepanel.hexanenetworks.com/Interface/Base/Home.aspx) when logged in

**Expected behavior**
the add widget box will be sticking out of its parent.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Windows 10 Version 1809 build 17763.292
- Browser Firefox nightly 67.0a1 (2019-01-29)(64bit)

**Additional context**
this will fix it 
```CSS
#ContentPlaceHolderMain_Home1_WidgetContainerHome_PanelConfiguration {
    border-top-right-radius: 10px;
}

**Comment by Hyrogenic** [comment]
Fixed in Beta Version **1.2**
