### ISSUE TITLE
Gametracker module/widget not working

### ISSUE THREAD

**Issue by Lazaruz88** [HexaneNetworks/gamepanel-dev#14]
**Bug**
Gametracker module/widget not working

**To Reproduce**
1. Log into https://gamepanel.hexanenetworks.com/
2. Click on the cogwheel, top right.
3. Fill in info and click "Add"
4. You cannot select IP or service.

**Screenshots**
![Screenshot/Gif](http://lazaruz.pro/i/bryd.gif)

**Desktop):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by stubbo** [comment]
😠
![gif](http://lazaruz.pro/i/bryd.gif)

**Comment by Hyrogenic** [comment]
We disabled gametracker integration for the panel recently due to them changing their API url without telling anyone. They haven't responded with a new API yet. 

Once we receive a new API url from gametracker, we can enable/fix it. 

Broken API Url: https://webapi.gametracker.com/gt.php
