### ISSUE TITLE
Reduce the size of the loading icon/logo

### ISSUE THREAD

**Issue by Hyrogenic** [HexaneNetworks/gamepanel-dev#20]
Reduce the size of the loading logo/icon as it's too large currently.

**Comment by stubbo** [comment]
I feel like it can just be removed, don't see the need for it.

**Comment by Hyrogenic** [comment]
Without a loading icon/logo between when browsing (ie. clicking through folders in the file manager), users won't be aware of when it's processing their request.

**Comment by havasuit** [comment]
**Describe alternatives you've considered**  
People having brains.

**Comment by stubbo** [comment]
If you are insistent on something to indicate then i would rather some thing like [codepen example](https://codepen.io/danielmorosan/pen/XmYBVx)
never really liked spinning things personally

**Comment by Hyrogenic** [comment]
Updated in Beta Version **1.2** to a simpler, smaller pre-loader.
