### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by ArchieeR** [HexaneNetworks/gamepanel-dev#21]
**Not sure if these are mentioned already : )**
Where is says the server players and restart button, change the background to soemthing like this. But better colours etc
https://i.imgur.com/y0IebUE.png

Make this text a darker colour: 
https://i.imgur.com/Y3UIZQ3.png

**Comment by Hyrogenic** [comment]
Thank you for the suggestions.

We're planning to change the boxes to another colour/texture soon as mentioned in another issue.

The darker text there is a good suggestion and we'll work on that.
