### ISSUE TITLE
Changes to the Square Textured Background Components

### ISSUE THREAD

**Issue by Hyrogenic** [HexaneNetworks/gamepanel-dev#3]
A few users suggested removing/changing the textured background on some of the core elements due to it not fitting in. 

Change:

- Experiment with another type of pattern which is more transparent

- Experiment by removing the texture and changing it to a solid colour or gradient

**Comment by havasuit** [comment]
You can prepend the url section of the background property with a linear-gradient to simulate a lower opacity version of the background.

[Example](https://objects.black-out.xyz/b8c9e4d)

Alternatively, there are tons of other svg backgrounds here (so they'll scale nicely): http://www.heropatterns.com/

**Comment by Hyrogenic** [comment]
Updated in Beta Version **1.3**
