### ISSUE TITLE
Misaligned Modules

### ISSUE THREAD

**Issue by kierancrossley** [HexaneNetworks/gamepanel-dev#30]
**Describe the bug**
Misaligned on homepage

**To Reproduce**
1. Go to the gamepanel login
2. Login
3. Go to home and look on the right

**Expected behavior**
Aligned properly

**Screenshots**
https://gyazo.com/4fe864939b23e23329ec2fd8b6cf5f79

**Desktop (please complete the following information):**
 - OS: WIndows
 - Browser: Chrome
 - Version: Latest

**Smartphone (please complete the following information):**
N/A

**Additional context**
Hyro said he also needed to fix cache for icons

**Comment by Hyrogenic** [comment]
Fixed in Beta Version **1.2**
