### ISSUE TITLE
Grid settings issue

### ISSUE THREAD

**Issue by stubbo** [HexaneNetworks/gamepanel-dev#31]
**Describe the bug**
Incorrect text color and box being cut short

**To Reproduce**
Go to the sub users page and click on "Grid Settings"

**Expected behavior**
text in the "pop up" will be black and the bottom will bet cut off

**Screenshots**
![oops](https://img.stubbo.me/6OHmG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Comment by Hyrogenic** [comment]
Updated in Beta Version **1.3**
