### ISSUE TITLE
Reset Password Box Misplacement 

### ISSUE THREAD

**Issue by Mitch123413** [HexaneNetworks/gamepanel-dev#33]
**Describe the bug**
The logo clips into box

**To Reproduce**
2. Click on 'Forgot your password?'
![image](https://user-images.githubusercontent.com/24734120/52432639-df6e7d80-2b02-11e9-8d5b-20e72664988e.png)

**Expected behavior**
Misplacement?

**Screenshots**
![image](https://user-images.githubusercontent.com/24734120/52432619-ca91ea00-2b02-11e9-9b0e-12d2245841ff.png)

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [Chrome]
 - Version [Not even know]

**Comment by Hyrogenic** [comment]
Fixed in Beta Version **1.2**
